title: Miranda Gemme-Ellis
#logo: /assets/img/headshot_circle.png
#description: text below image... Recent graduate from Merrimack College Master's Program
#show_downloads: true
theme: jekyll-theme-minimal

